repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: end-of-file-fixer
          - id: check-json
          - id: check-yaml
          - id: check-xml
          - id: check-merge-conflict
          - id: no-commit-to-branch
            args: [--branch, master]
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: 'v2.2.1'
      hooks:
          - id: prettier
            exclude: .github/ISSUE_TEMPLATE
